In [9]:
import torch

# Create a Tensor with just ones in a column
a = torch.ones(5)
print(a)

# Create a Tensor with just zeros in a column
b = torch.zeros(5)
print(b)

print(torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])) # custom valued tensor

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0.])
tensor([1., 2., 3., 4., 5.])


In [6]:
print(torch.zeros(3,2))
print(torch.ones(3,2))
print(torch.tensor([[1.0, 2.0],[3.0, 4.0]]))

# 3D Tensor
g = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(g)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [10]:
# We can also find out the shape of a Tensor using .shape method.
print(a.shape)
print(g.shape)

torch.Size([5])
torch.Size([2, 2, 2])


In [13]:
# Access Tensor elements
print(c[2])

# All indices starting from 0

# Get element at row 1, column 0 by any of these ways:
print(g[1,0,0])
print(g[1][0][0])

tensor(3.)
tensor(5.)
tensor(5.)


In [14]:
# How to access entire rows:

# All elements
print(g[:])

# All elements from index 1 to 2 (inclusive)
print(a[1:3])

# All elements till index 4 (exclusive)
print(a[:4])

print(g[0,:])

# Second column
print(g[:,1])

tensor([2., 3.])
tensor([1., 2., 3., 4.])
tensor([1., 2.])
tensor([2., 4.])


In [16]:
#----------------------------------------------------------------------------------------------
#   Specify data type of elements
#----------------------------------------------------------------------------------------------
#   Whenever we create a tensor, PyTorch decides the data type of the elements of the tensor 
#   such that the data type can cover all the elements of the tensor. We can override this by 
#   specifying the data type while creating the tensor.

int_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(int_tensor.dtype)

# What if we changed any one element to floating point number?
int_tensor = torch.tensor([[1,2,3],[4.,5,6]])
print(int_tensor.dtype)
print(int_tensor)

# This can be overridden as follows
int_tensor = torch.tensor([[1,2,3],[4.,5,6]], dtype=torch.int32)
print(int_tensor.dtype)
print(int_tensor)


torch.int64
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [17]:
#----------------------------------------------------------------------------------------------
#   Tensor to/from NumPy Array
#----------------------------------------------------------------------------------------------
#
# 	We have mentioned several times that PyTorch Tensors and NumPy arrays are pretty similar. 
# 	This raises the question if it’s possible to convert one data structure into another.
# 	Let’s see how we can do this.

# Import NumPy
import numpy as np
	 
# Tensor to Array
g_numpy = g.numpy()
print(g_numpy)

# Array to Tensor
h = np.array([[8,7,6,5],[4,3,2,1]])
h_tensor = torch.from_numpy(h)
print(h_tensor)

[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
tensor([[8, 7, 6, 5],
        [4, 3, 2, 1]])


In [18]:
#----------------------------------------------------------------------------------------------
#	Arithmetic Operations on Tensors
#----------------------------------------------------------------------------------------------
#
#	Now it’s time for the next step. Let’s see how we can perform arithmetic operations on PyTorch tensors.

# Create tensor
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[-1,2,-3],[4,-5,6]])
	 
# Addition
print(tensor1+tensor2)

# We can also use
print(torch.add(tensor1,tensor2))

# Subtraction
print(tensor1-tensor2)

# We can also use
print(torch.sub(tensor1,tensor2))

tensor([[ 0,  4,  0],
        [ 8,  0, 12]])
tensor([[ 0,  4,  0],
        [ 8,  0, 12]])
tensor([[ 2,  0,  6],
        [ 0, 10,  0]])
tensor([[ 2,  0,  6],
        [ 0, 10,  0]])


In [19]:
# Multiplication

# Tensor with Scalar
print(tensor1 * 2)

# Tensor with another tensor
# Elementwise Multiplication
print(tensor1 * tensor2)

# Matrix multiplication
tensor3 = torch.tensor([[1,2],[3,4],[5,6]])
print(torch.mm(tensor1,tensor3))


tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[ -1,   4,  -9],
        [ 16, -25,  36]])
tensor([[22, 28],
        [49, 64]])


In [20]:
# Division

# Tensor with scalar
print(tensor1/2)

# Tensor with another tensor
# Elementwise division
print(tensor1/tensor2)

tensor([[0, 1, 1],
        [2, 2, 3]])
tensor([[-1,  1, -1],
        [ 1, -1,  1]])


In [21]:
#----------------------------------------------------------------------------------------------
#	CPU v/s GPU Tensor
#----------------------------------------------------------------------------------------------
#
#   PyTorch has different implementation of Tensor for CPU and GPU. 
#   Every tensor can be converted to GPU in order to perform massively parallel, fast computations. 
#   All operations that will be performed on the tensor will be carried out using GPU-specific 
#   routines that come with PyTorch. If you don’t have access to a GPU, you can perform these 
#   examples on Google Colab. Select GPU as Runtime. Let’s first see how to create a tensor for GPU.


# Create a tensor for CPU > This will occupy CPU RAM
tensor_cpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cpu')
	 
# Create a tensor for GPU > This will occupy GPU RAM
tensor_gpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cuda')

# If you are using Google Colab, focus on the RAM consumption meter in the top right corner and 
# you will see the GPU RAM consumption increase as soon as you create tensor_gpu.

# Just like tensor creation, the operations performed for CPU and GPU tensors are also different and consume RAM corresponding to the device specified.

# This uses CPU RAM
tensor_cpu = tensor_cpu * 5

# This uses GPU RAM > Focus on GPU RAM Consumption
tensor_gpu = tensor_gpu * 5

# The key point to note here is that no information flows to CPU in the GPU tensor operations (except if we print or access the tensor).
# We can move the GPU tensor to CPU and vice versa as shown below.

# Move GPU tensor to CPU
tensor_gpu_cpu = tensor_gpu.to(device='cpu')

# Move CPU tensor to GPU
tensor_cpu_gpu = tensor_cpu.to(device='cuda')

AssertionError: Torch not compiled with CUDA enabled